projeto/core/urls.py
from django.urls import path
from projeto.core import views as v


app_name = 'core'


urlpatterns = [
    path('', v.index, name='index'),
]

projeto/produto/urls.py
from django.urls import path
from projeto.produto import views as v


app_name = 'produto'


urlpatterns = [
    path('', v.produto_list, name='produto_list'),
    path('<int:pk>/', v.produto_detail, name='produto_detail'),
    path('add/', v.ProdutoCreate.as_view(), name='produto_add'),
]

projeto/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
	path('', include('projeto.core.urls')),
	path('produto/', include('projeto.produto.urls')),
    path('admin/', admin.site.urls),
]

projeto/core/models.py
from django.db import models

# Create your models here.
class TimeStampedModel(models.Model):
    created = models.DateTimeField(
        'criado em',
        auto_now_add=True,
        auto_now=False
    )
    modified = models.DateTimeField(
        'modificado em',
        auto_now_add=False,
        auto_now=True
    )

    class Meta:
        abstract = True

projeto/estoque/models.py
from django.contrib.auth.models import User
from django.db import models
from projeto.core.models import TimeStampedModel
from projeto.produto.models import Produto



MOVIMENTO = (
	('e', 'entrada'),
	('s', 'saida'),
)

class Estoque(TimeStampedModel):
	funcionario = models.ForeignKey(User, on_delete=models.CASCADE, blank=True)
	nf = models.PositiveIntegerField('nota fiscal', null=True, blank=True)
	movimento = models.CharField(max_length=1, choices=MOVIMENTO, blank=True)

	class Meta:
		ordering = ('-created',)

	def __str__(self):
		return str(self.pk)

class EstoqueItens(models.Model):
    estoque = models.ForeignKey(Estoque,on_delete=models.CASCADE,related_name='estoques')
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    quantidade = models.PositiveIntegerField()
    saldo = models.PositiveIntegerField(blank=True)

    class Meta:
    	ordering = ('pk',)

    def __str__(self):
        return '{} - {} - {}'.format(self.pk, self.estoque.pk, self.produto)

projeto/produto/models.py
from django.db import models
from django.urls import reverse_lazy

class Produto(models.Model):
    importado = models.BooleanField(default=False)
    ncm = models.CharField('NCM', max_length=8)
    produto = models.CharField(max_length=100, unique=True)
    preco = models.DecimalField('preço', max_digits=7, decimal_places=2)
    estoque = models.IntegerField('estoque atual')
    estoque_minimo = models.PositiveIntegerField('estoque mínimo', default=0)

    class Meta:
        ordering = ('produto',)

    def __str__(self):
        return self.produto 
    
    def get_absolute_url(self):
        return reverse_lazy('produto:produto_detail', kwargs={'pk': self.pk})

   

projeto/produto/forms.py
from django import forms
from models import Produto

class ProdutoForm(forms.ModelForm):

    class Meta:
        model = Produto
        fields = '__all__'

projeto/core/views.py
from django.shortcuts import render

def index(request):
	return render(request, 'index.html')

projeto/estoque/views.py
from django.shortcuts import render

# Create your views here.

projeto/produto/views.py
from django.shortcuts import render
from django.views.generic import CreateView
from .models import Produto
from .forms import ProdutoForm
# Create your views here.

def produto_list(request):
    template_name = 'produto_list.html'
    objects = Produto.objects.all()
    context = {'object_list': objects}
    return render(request, template_name, context)

def produto_detail(request ,pk):
    template_name = 'produto_detail.html'
    obj = Produto.objects.get(pk=pk)
    context = {'object': obj}
    return render(request, template_name, context)

def produto_add(request):
    template_name = 'produto_form.html'
    return render(request, template_name)


class ProdutoCreate(CreateView):
    model = Produto
    template_name = 'produto_form.html'
    form_class = ProdutoForm

projeto/core/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="https://www.djangoproject.com/favicon.ico">
    <title>Estoque Moura</title>


    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- Font-awesome -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
 
    <style>
      body{
        margin-top: 60px;
      }
      .ok{
        color: green;
      }
      .no{
        color: red;
      }
  </style>
  {% block css %}{% endblock css %}

    
  </head>
  <body>
    {% include "includes/nav.html"%}
    <div class="container">
      {% block content %}{% endblock content %}
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    {% block js %}{% endblock js %}
  </body>
</html>

projeto/core/templates/includes/nav.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="#">Estoque</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{%url 'core:index' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{%url 'produto:produto_list' %}">Produtos</a>
            </li>
          
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Estoque</a>
                <div class="dropdown-menu" aria-labelledby="dropdown01">
                    <a class="dropdown-item" href="#">Entrada</a>
                    <a class="dropdown-item" href="#">Saida</a>
                </div>
            </li>
        </ul>
    </div>
</nav>

projeto/core/templates/index.html
{% extends "base.html" %}

{% block content %}

<div class="jumbotron">
  <div class="container">
    <h1>Bem-vindo!</h1>
    <p>Este é um sistema para controle de estoque.</p>
  </div>
</div>

{% endblock content %}

projeto/produto/templates/produto_detail.html
{% extends "base.html" %}

{%block content%}

<a href="{%url 'produto:produto_list'%}">Voltar</a>
<h1>{{object}}
    <span class="pull-right">
        <a href="">
            <button type="button" class="btn btn-success">
                <span class="fa fa-pencil"></span> Editar
            </button>
        </a>
    </span>
</h1>
<div class="col-sm-6">
  <table class="table table-user-information">
        <tbody>
            <tr>
                <th class="text-right">Importado</th>
                <td>
                    {% if object.importado %}
                    <i class="fa fa-check-circle ok"></i>
                    {% else %}
                    <i class="fa fa-minus-circle no"></i>
                    {% endif %}
                </td>
            </tr>
            <tr>
                <th class="text-right">NCM</th>
                <td>{{ objct.ncm}}</td>
            </tr>
            <tr>
                <th class="text-right">Preço</th>
                <td>R${{object.preco}}</td>
            </tr>
            <tr>
                <th class="text-right">Estoque</th>
                <td>{{object.estoque}}</td>
            </tr>
            <tr>
                <th class="text-right">Estoque mínimo</th>
                <td>{{object.estoque_minimo}}</td>
            </tr>
            <tr>
        </tbody>
    </table>
</div>
{%endblock content%}

projeto/produto/templates/produto_form.html
{%extends "base.html"%}

{% load widget_tweaks %}

{%block content%}
<form method="POST" novalidate>
    {% csrf_token %}
    {% for field in form.visible_fields %}
      <div class="form-group{% if field.errors %} has-error {% endif%}">
        <label for="{{ field.id_for_label }}">
          {% if field.field.required %}
            <span class="required">{{ field.label }} </span>
          {% else %}
            {{ field.label }}
          {% endif %}
        </label>
        {% render_field field class="form-control" %}
        {% for error in field.errors %}
          <span class="text-muted">{{ error }}</span>
        {% endfor %}
      </div>
    {% endfor %}
    <button type="submit" class="btn btn-success">Cadastrar</button>
  </form>

{%endblock content%}

projeto/produto/templates/produto_list.html
{% extends "base.html" %}


{% block content %}

  <div class= "page-header">
    <h2>Lista de Produtos
      <span class="pull-right">
        <a href="{%url 'produto:produto_add' %}">
          <button type="button" class="btn btn-primary">
            <span class = "fa fa-plus"></span>Adicionar
          </button>
        </a>
      </span>
    </h2>
    
    {% if object_list %}
    
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Importado</th>
            <th>NCM</th>
            <th>Produto</th>
            <th>Preço</th>
            <th class="text-center">Estoque</th>
            <th class="text-center">Estoque mínimo</th>
          </tr>
        </thead>
        <body>
          {%for object in object_list%}
            <tr>
              <td>
                {%if object.importado%}
                <i class="fa fa-check-circle ok"></i>
                {%else%}
                  <i class="fa fa-minus-circle no"></i>
                {%endif%}
              </td>
              <td>{{object.ncm}}</td>
              <td>
                <a href="{{ object.get_absolute_url }}">{{object.produto}}</a>
              </td>
              <td>R$<span class = "pull-right">{{object.preco}}</span></td>
              <td class="text-center">{{object.estoque}}</td>
              <td class="text-center">{{object.estoque_minimo}}</td>
            </tr>
          {%endfor%}  
        </body>
    </table>
  {%else%}
  <p class="alert alert-warning">Sem itens na lista</p> 
  {%endif%}
  </div>

{% endblock content %}